# Generated by Django 3.1.5 on 2021-01-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadpdf',
            name='name',
            field=models.FileField(upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='uploadpdf',
            name='uploadDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
